-- 开源软件信息表
CREATE TABLE IF NOT EXISTS `oss_software_info` (
    `id` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `sw_name` VARCHAR(128) NOT NULL COMMENT '软件名称',
    `sw_category` VARCHAR(12) NOT NULL DEFAULT 'BASE' COMMENT '软件分类: BASE-开源基础软件, TOOL-开源工具软件, CMPNT-开源组件',
    `sw_type` VARCHAR(12) NOT NULL DEFAULT 'MAIN' COMMENT '软件类型: MAIN-主推软件, LIMIT-非主推软件, QUIT-已退出软件',
    `rsp_team_id` VARCHAR(32) DEFAULT NULL COMMENT '责任团队ID',
    `rsp_team_name` VARCHAR(64) DEFAULT NULL COMMENT '责任团队名称',
    `rsp_user_id` VARCHAR(32) DEFAULT NULL COMMENT '责任人ID',
    `rsp_user_name` VARCHAR(100) DEFAULT NULL COMMENT '责任人姓名',
    `product_type` VARCHAR(32) DEFAULT NULL COMMENT '产品类型',
    `recommended_version` VARCHAR(64) DEFAULT NULL COMMENT '主推荐使用版本',
    `application_scene` VARCHAR(1024) DEFAULT NULL COMMENT '应用场景',
    `data_src_flag` VARCHAR(2) DEFAULT NULL COMMENT '数据来源: 0-人工引入, 1-异地同步',
    `sync_datetime` DATETIME DEFAULT NULL COMMENT '同步时间',
    `batch_date` VARCHAR(32) DEFAULT NULL COMMENT '批次日期',
    `create_mode` INT(10) NOT NULL DEFAULT 0 COMMENT '创建方式: 0-本系统创建, 1-异地同步',
    `create_user_id` VARCHAR(32) DEFAULT NULL COMMENT '创建者',
    `create_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_user_id` VARCHAR(32) DEFAULT NULL COMMENT '更新者',
    `update_datetime` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `logic_status` INT(10) NOT NULL DEFAULT 0 COMMENT '逻辑状态: 0-正常, 1-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_sw_name` (`sw_name`),
    KEY `idx_sw_category` (`sw_category`),
    KEY `idx_sw_type` (`sw_type`),
    KEY `idx_rsp_team_id` (`rsp_team_id`),
    KEY `idx_logic_status` (`logic_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='开源软件信息表';
